
#		Dockerfile  3.09.86  2018-06-24_22:25:49_CDT  https://github.com/BradleyA/pi-display  uadmin  two-rpi3b.cptx86.com 3.08  
#		   completed prototype controling blinkt from container start with docker-compose 
FROM blinkt
COPY rainbow.py .
CMD ["python", "rainbow.py"]
