FROM resin/rpi-raspbian:jessie
#	Dockerfile.test.notes  3.19.118  2018-06-29_07:27:09_CDT  https://github.com/BradleyA/pi-display  uadmin  two-rpi3b.cptx86.com 3.18  
#	   move .py file to test in container 

RUN apt-get update -qy && apt-get install -qy \
    python2.7 \
    python-rpi.gpio

RUN curl https://get.pimoroni.com/blinkt | /bin/bash

# Cancel out any Entrypoint already set in the base image.
ENTRYPOINT []	

WORKDIR /root/

WORKDIR /root/
COPY set_pixel01.py set_pixel01.py
WORKDIR /root/

CMD ["python", "set_pixel01.py"]

